[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[tool.maturin]
manylinux = "off"
sdist-include = ["duckling-ffi/*"]

# [build-system]
# requires = ["setuptools", "wheel", "setuptools-rust"]
